apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: eaas-repo-caas-test
  project: caas-test
spec:
  agents:
  - name: eaas-agent-caas-test
  credentials:
    password: sealed://credentials.password
    username: hardik-rafay
  endpoint: https://github.com/hardik-rafay/envmgr.git
  secret:
    name: file://artifacts/eaas-repo-caas-test/sealed-secret.yaml
  type: Git
