apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: aws-caas-test
  project: caas-test
spec:
  secret:
    name: file://artifacts/aws-caas-test/sealed-secret.yaml
  variables:
  - name: rolearn
    options:
      override:
        type: allowed
      required: true
      sensitive: true
    value: sealed://variables.0
    valueType: text
  - name: externalid
    options:
      override:
        type: allowed
      required: true
      sensitive: true
    value: sealed://variables.1
    valueType: text
status: {}
