
apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  description: Updated variables
  name: rafay-eks-rs-tmpl-caas-test
  project: caas-test
spec:
  agents:
  - name: eaas-agent-caas-test
  contexts:
  - name: rafay-caas-test
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/aws/101-caas-eks/terraform/eks
    name: eaas-repo-caas-test
  variables:
  - name: managed_nodegroups
    options:
      override:
        type: allowed
      required: true
    value: |-
      {
        "ng-1" = {
          ng_name         = "infra-terraform"
          node_count      = 2
          node_max_count  = 3
          node_min_count  = 1
          k8s_version     = "1.26"
          instance_type   = "t3.large"
        }
      }
    valueType: hcl
  - name: cluster_tags
    options:
      override:
        type: allowed
      required: true
    value: |-
      {
          "email" = "email@rafay.co"
          "env"    = "dev"
          "orchestrator" = "rafay"
      }
    valueType: hcl
  - name: base_blueprint_name
    options:
      override:
        type: notallowed
      required: true
    value: minimal
    valueType: text
  version: v1
