apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-caas-test
  namespace: default
spec:
  encryptedData:
    variables.0: AQBeT+2EYPAyBjz5IBWLxD3Qdb6/MIgZEXXLvuELvXc13K70+nSekWPcqc8AlrpsOhdlmQ62epJEumLg3MdsBS6WDNJkIsnL9o7togPG8qWOUHvN7MYcKN9eDSV26FuhRIS5L+TlDEpVEfO+sX2M2iQhplq3lVAs/zEqeV84XGvGQ5epcTo96adzSz/y9IaIlhneHmqEPlCzY5kTkkLUz1HlGHmrsoKQC3DhaDG+O99+ASpUTYaRG5CMpRNzBAr9lgdWbuTCtvMdXTaBCkYMKemBWx2IfyjliPAYm4M1nxCZBbHDfwWjI7EY3BUVqE+4qFbgAssJl/HQ90ZIiOmZYkpnftsSAimenAbZNrjnq5OrHLjfrOyIlDBVu2f4Bw==
    variables.1: AQB2b3EflShAqFVK9qvLseINsvItGh2lHKhHQQvudV5lfO5h65PQfnnfZDQvGAz6v3tg1VYlt2a5eIs5B5j+YsGxq/So7TeYG/0i+LfwzqEq2USg/T3jRjAIr2QUHORzX/3eJ1pqH+4mwPEZyyTV4zvVCUTweG2jjXdtkyS7/nE2HoIaak9ZtioowheHWxWulMpic4lvU7U/oHzRfjmJRNqQSQSB0lSio5lkSLi2kPkwlu17HsIpVjQOfNUONCt2sL5qMYKp8bqUTHXPZMBkh6hBFsIFtlUt06CQcCavoAttoc8yKtfBSUOczUCAD7l4Pa2LltRW+NxA4hqugVLU9FB+TiCpq5qo2yPlavdMqPLxfJ7BRcq4SmyVBhaxQg==
  template:
    metadata:
      creationTimestamp: null
      name: aws-caas-test
      namespace: default

