apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rafay-caas-test
  namespace: default
spec:
  encryptedData:
    RCTL_API_KEY: AQANWvjUFrLTnV7TtWtlEwx8FgG9Elqdheq9HexMvK2N+TFE0/SOzhIhZjX3PEOieaW1xnZ0krPwZ3x00YaGTOmaTw3xGL6KH+Q493iYnqkALP+89eJiM41Y9VIylHZ2kEw9Wco3kc5MlmErg9c+RiQ0jnU+03GaoGtnKUREKk9Zpmh192BXcz3H58GKZRRNjYWm17VW23hIe1iSRgzgGn5n4tMCp973WYPOVX8BMGwkL/KQgaforKN2SEQsCcGuJdCwEYOHlJ8k76zHKvscTEYUQrQugTDIj6wIOj0CPQFRx/iF1bjKYoQXrhKF8Y0hZqNDV9Z94XAyczC8ZCXo6mdjv2ZoSygcWpoivzq3elapQFJD+mdouUuV4lRAvw==
    RCTL_API_SECRET: AQAmjjSdfAhgn3KvkNSh/T53dtn7FxUbNQB/DOl0A7JdjILFA/DnfIQMvyxYLR9rGoDdA/pkQ7xiUYycUUK7Li9FRlgjFePePxfBacGiraOuojN3n8EdDvxUhzcskl/5Y/8FfsGcgwM3lMBzqX+UGoVeDtlkWv3Eu70dO7I3or7wqwQIe5Doz2tOexnp7KTIJB6PSxE5aV0/0ycBf2d6Pj2QFhxu7BORNXSCscshCtg7km4JLtygESkWDMKO9tkdzH+iNR4S377M5tPimnsCdwXP3j8lUFDfinOvrM9Xs16qNii5qsE/etmTYDMbTFBb19WnQwhON/DFf3zvLFxmmdibxqfSoTZNi9EyEMTHv2+nzSawYUW91/RZw3CYpw==
  template:
    metadata:
      creationTimestamp: null
      name: rafay-caas-test
      namespace: default

